# Generated by Django 5.1 on 2024-08-14 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialuser',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
