# Generated by Django 5.1 on 2024-08-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_contact_socialuser_following_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_form',
            new_name='user_from',
        ),
    ]
