# Generated by Django 5.1 on 2024-11-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_socialuser_message_notification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
