# Generated by Django 5.1 on 2024-11-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_delete_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialuser',
            name='reason_deleting_account',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
