# Generated by Django 5.1 on 2025-02-03 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_storyvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='file',
            field=models.FileField(upload_to='stories/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
